version: "3.8"
services:
    database: # local database, used for development
        container_name: db
        image: postgres:latest
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/
        env_file:
            - .env.dev
        environment:
            - POSTGRES_USER: ${DATABASE_USER}
            - POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            - POSTGRES_DB: ${DATABASE_NAME}
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
        restart: unless-stopped
        volumes:
            - .:/usr/src/app/
        env_file:
            - .env.dev
        ports:
            - "8000:8000"
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        environment:
            - discovery.type=single-node
            - http.cors.allow-origin="*"
            - "http.cors.enabled=true"
            - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
            - "http.cors.allow-credentials=true"
        ports:
            - "9200:9200"
        volumes:
            - esdata:/usr/share/elasticsearch/data
    redis:
        container_name: redis
        restart: always
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
    nginx:
        container_name: nginx
        restart: unless-stopped
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - app
        volumes:
            - ./nginx/dev:/etc/nginx/conf.d
volumes:
    redisdata:
    esdata:
    database-data:
